language: java

before_script:
  - cd releng

script: 
  - mvn clean compile install
 
before_deploy:
  - cd ..
 
deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file_glob: true
  overwrite: true
  file: 
    - builds/bin/*.zip
    - builds/bin/*.tgz
    - builds/bin/*.tar.gz
  skip_cleanup: true
  on:
    tags: true

